### ISSUE TITLE
random dropouts

### ISSUE THREAD

**Issue by toniMephis** [khoih-prog/SAMD_Slow_PWM#4]
Arduino IDE version: 1.8.19 (Windows 1.8.57.0)
Arduino SAMD Core Version 1.8.12
ARDUINO_SAMD_MKRWIFI1010
OS: Windows10
sketch: example ISR_Modify_PW
![Clipboard06](https://user-images.githubusercontent.com/100749721/156494955-7051a95b-e18c-470b-a3d8-0f976f2d0882.png)
M

**Comment by khoih-prog** [comment]
Hi @toniMephis 

Thanks again for this bug report.

The bug just affects the terminal **display** of the `New Period`, but thankfully not the real PWM operation.

This, as well as [float precisison of DutyCycle only sometimes working #3](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/3) will be fixed in the next release.

Regards,

**Comment by khoih-prog** [comment]
Hi @toniMephis 

The new [**SAMD_Slow_PWM releases v1.2.3**](https://github.com/khoih-prog/SAMD_Slow_PWM/releases/tag/v1.2.3) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/SAMD_Slow_PWM#contributions-and-thanks)

Best Regards,

---

### Releases v1.2.3

1. Fix `DutyCycle` bug. Check [float precisison of DutyCycle only sometimes working #3](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/3)
2. Fix `New Period` display bug. Check [random dropouts #4](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/4)
3. Update examples
